### PR TITLE
Add new pull request template

### PR DESCRIPTION
**Pull request by mpxr**
Mix it up!

We need a new PR template.

Please, people, tell me your thoughts and anything you'd like to add here.

### CODE REVIEW

**Review by hannah2503 — COMMENTED** [review]
Love!! 

Would it be useful to have a bit about "What a reviewer/QA should look out for?" 

Otherwise I'm all aboard champ!

**Review by tschoffelen — APPROVED** [review]
LOVE THIS ❤️

**Review by joeleg — APPROVED** [review]
yes please

**Comment by mpxr** [comment]
> Would it be useful to have a bit about "What a reviewer/QA should look out for?"

I'm worried that if we give the reviewer directions on what to focus on, there might be other important bits in the PR that could be missed.

**Comment by hannah2503** [comment]
> > Would it be useful to have a bit about "What a reviewer/QA should look out for?"
> 
> I'm worried that if we give the reviewer directions on what to focus on, there might be other important bits in the PR that could be missed.

Ok that's a fair concern. I suppose I was thinking from the point of view of a complex change it's not always easy to know what to check if you don't have the full context but maybe the individual should make a judgement call when submitting their PR on when to guide and when to leave it up to the reviewer 👍

**Review by hannah2503 — APPROVED** [review]
Thanks @mpxr !

**Pull request merged**
